My\RecipesBundle\Entity\Recipe:
  type: entity
  repositoryClass: My\RecipesBundle\Repository\RecipeRepository
  table: recipes
  manyToOne:
    author:
      targetEntity: Author
      joinColumn:
        name: author_id
        referencedColumnName: id
        onDelete: "CASCADE"
      cascade: ["persist"]
      inversedBy: recipes
  manyToMany:
    ingredients:
      targetEntity: Ingredient
      joinTable:
        name: recipe_ingredients
        joinColumns:
          recipe_id:
            referencedColumnName: id
        inverseJoinColumns:
          ingredient_id:
            referencedColumnName: id
      cascade: ["persist"]
  id:
    id:
      type: integer
      generator: {strategy: AUTO}
  fields:
    name:
      type: string
      length: 255
    difficulty:
      type: string
      length: 40
    description:
      type: text