homepage:
    pattern:   /
    defaults:  { _controller: AppBundle:Default:show }

recipes_list:
  path:     /recipes-list
  defaults: { _controller: MyRecipesBundle:Recipe:list }

recipe_show:
  path:     /recipe/{id}
  defaults: { _controller: MyRecipesBundle:Recipe:show }
  
authors_list:
  path:     /authors-list
  defaults: { _controller: MyRecipesBundle:Author:list }