homepage:
  pattern:  /
  defaults: { _controller: AppBundle:Default:show }

recipes:
  path:     /{_locale}/recipes
  defaults: { _controller: MyRecipesBundle:Recipe:list }
  requirements:
    _locale: '%app.locales%'

karlos_recipes_list:
  path:     /karlos-recipes-list
  defaults: { _controller: MyRecipesBundle:Recipe:karloslist }

recipe_show:
  path:     /recipe/{id}/{slug}
  defaults: { _controller: MyRecipesBundle:Recipe:show }
  requirements:
    id:  \d+
    slug: ".+"

recipe_create:
  path:     /recipe-create
  defaults: { _controller: MyRecipesBundle:Recipe:create }

recipe_modify:
  path:     /recipe-modify/{id}
  defaults: { _controller: MyRecipesBundle:Recipe:modify }
  requirements:
    id:  \d+
  
authors:
  path:     /{_locale}/authors-list
  defaults: { _controller: MyRecipesBundle:Author:list }
  requirements:
    _locale: '%app.locales%'
    
author_show:
  path:     /author/{id}
  defaults: { _controller: MyRecipesBundle:Author:show }
  
author_create:
  path:     /author-create
  defaults: { _controller: MyRecipesBundle:Author:create }
  
author_modify:
  path:     /author-modify/{id}
  defaults: { _controller: MyRecipesBundle:Author:modify }
  requirements:
    id:  \d+
    
ingredients:
  path:     /{_locale}/ingredients-list
  defaults: { _controller: MyRecipesBundle:Ingredient:list }
  requirements:
    _locale: '%app.locales%'
  
ingredient_create:
  path:     /ingredient-create
  defaults: { _controller: MyRecipesBundle:Ingredient:create }
  
ingredient_modify:
  path:     /ingredient-modify/{id}
  defaults: { _controller: MyRecipesBundle:Ingredient:modify }
  requirements:
    id:  \d+