My\UserBundle\Entity\User:
    type: entity
    table: fos_user
    repositoryClass: My\UserBundle\Entity\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        active:
          type: boolean
          length: null
            
    lifecycleCallbacks: {  }
